read: [.aider_conventions.md, share.md]
# file: share.md

# ===============================================================
# MODELS
# ===============================================================

## expensive:
# model: openrouter/google/gemini-2.5-pro-preview-06-05        # 1.25/10.0 | 1.0
#model: openrouter/anthropic/claude-3.7-sonnet                # 3.00/15.0 | 0.2
model: openrouter/anthropic/claude-sonnet-4                  # 3.00/15.0 | 0.2

# mid
#model: openrouter/google/gemini-2.5-flash                    # 0.30/2.50 | 1.0
# model: openrouter/deepseek/deepseek-r1                       # 0.45/2.15 | 0.1
# model: openrouter/deepseek/deepseek-r1-0528                  # 0.50/2.15 | 0.1
# model: openrouter/anthropic/claude-3.5-haiku                 # 0.80/4.00 | 0.2

## cheap but reasonable:
# model: openrouter/google/gemini-2.5-flash-lite-preview-06-17 # 0.10/0.40 | 1.0
# model: openrouter/google/gemini-2.5-flash-preview-05-20      # 0.15/0.60 | 1.0
# model: openrouter/deepseek/deepseek-chat-v3-0324             # 0.30/0.88 | 0.1

# ===============================================================
# APPEARANCE
# ===============================================================
stream: false
cache-prompts: true
code-theme: solarized-light
light-mode: true

# ===============================================================
# HISTORY
# ===============================================================
# llm-history-file: .aider.llm.history
restore-chat-history: false
#max-chat-history-tokens: 1024

# ===============================================================
# TESTING (off)
# ===============================================================
#auto-test: true
#test-cmd: pytest -v -x test/logic/
#test-cmd: pytest -v -x -k 'local' test/logic/