[project]
name = "pyosc-wf"
version = "0.1.0"
description = "Waveform-specific components for PyOSC."
authors = [{ name = "Sam Scholten", email = "s.scholten@uq.edu.au" }]
requires-python = ">=3.8"
dependencies = [
    "pyosc-plot @ file:///${PROJECT_ROOT}/pyosc-plot",
    "loguru",
    "scipy",
    "numba",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

